document.querySelector("#generate").addEventListener("click", () => {
    generate();
  });
  
  generate = () => {
    var quotes = {
      "(Lie To Me - Black Atlass)": '"You are an angel, from the highest."',
      "(Heartbeat - Ghostly Kisses)": '"You are my only one. Moon and sun."',
      "(Heaven, Wait - Ghostly Kisses)": '"In every way you are in my heart. You make me feel like we were never apart. Never apart."',
      "(Blackbirds - Ghostly Kisses)": '"I would feel alive by your side."',
      "(A Different Kind of Love - Ghostly Kisses)": '"I have known a different kind of love. The kind that makes you whole."',
      "(Clay - Ghostly Kisses)": '"I wish I could bring you back now. And mold you from clay all for you."',
      "(Carry Me - Ghostly Kisses)": '"My love. No games. I miss you everyday."',
      "(Happy Together - Floor Cry)": '"The only one for me is you, and you for me."',
      "(Green Book - Ghostly Kisses)": '"Angel eyes are only meant to smile."',
      "(Your Heart is Gold - Ghostly Kisses)": '"Under the stars I want to be with you. Hold me tight like we used to."',
      "(Your Heart is Gold - Ghostly Kisses)": '"And though your heart is gold."',
      "(Don't Let Me Go - Cigarettes After Sex)": '"Do not let me go. Stay with me still. I have missed you so."',
      "(Heavenly - Cigarettes After Sex)": '"I am giving you all my, giving you all my, giving you all my love."',
      "(You're the Only Good Thing In My Life - Cigarettes After Sex)": '"You are the only good thing in my life."',
      "(Touch - Cigarettes After Sex)": '"Missing you only ever since we fell in love."',
      "(Falling In Love - Cigarettes After Sex)": '"I feel I am falling in love with all my heart."',
      "(K. - Cigarettes After Sex)": '"And I am kissing you lying in my room. Holding you until you fall asleep."',
      "(K. - Cigarettes After Sex)": '"Stay with me. I do not want you to leave..."',
      "(Sunsetz - Cigarettes After Sex)": '"Sunsets. I wanna hear your voice. A love that nobody could destroy."',
      "(Apocalypse - Cigarettes After Sex)": '"Your lips, my lips. Apocalypse."',
      "(Apocalypse - Cigarettes After Sex)": '"When you are all alone. I will reach for you. When you are feeling low. I will be there too."',
      "(Sweet - Cigarettes After Sex)": '"And I will gladly break it. I will gladly break my heart for you..."',
      "(Opera House - Cigarettes After Sex)": '"I have got a love for you, I just can not escape."',
      "(Opera House - Cigarettes After Sex)": '"I was meant to love you and always keep you in my life."',
      "(Opera House - Cigarettes After Sex)": '"I was meant to love you, I knew I loved you at first sight."',
      "(Nothing's Gonna Hurt You Baby - Cigarettes After Sex)": '"Nothing is gonna hurt you baby. As long as you are with me you will be just fine."',
      "(Nothing's Gonna Hurt You Baby - Cigarettes After Sex)": '"Nothing is gonna hurt you baby. Nothing is gonna take you from my side."',
      "(I'm a Firefighter - Cigarettes After Sex)": '"I need you here, I need your love. I need your love inside of mine, like I could die."',
      "(Dreaming of You - Cigarettes After Sex)": '"Want you all the time. And now I am dreaming, dreaming, dreaming, dreaming, dreaming of you."',
      "(Starry Eyes - Cigarettes After Sex)": '"When I am alone I hear and feel you. Wish that I could reach right out and touch you."',
      "(Affection - Cigarettes After Sex)": '"I think of you, I want you too, I would fall for you. It is affection always..."',
      "(Keep on Loving You - Cigarettes After Sex)": '"When I said that I love you I meant that I love you forever..."',
      "(Keep on Loving You - Cigarettes After Sex)": '"And I am gonna keep on loving you. Because it is the only thing I wanna do."',
      "(Keep on Loving You - Cigarettes After Sex)": '"I do not wanna sleep. I just wanna keep on loving you."',
      "(Crush - Cigarettes After Sex)": '"And now you are all I think about when I am alone. Can not wait to feel your love inside me now."',
      "(Sesame Syrup - Cigarettes After Sex)": '"I have had a long list of lovers, but none of them matter to me except you."',
      "(You're All I Want - Cigarettes After Sex)": '"There is no other love, it is only yours. You are all I want, all I love."',
      "(Pistol - Cigarettes After Sex)": '"You have been on my mind. And I will waste my time. Until you lift me off the floor and love me again."',
      "(Wish That You Were Here - Florence + The Machine)": '"You are always on my mind. Wish that you were here."',
      "(Lover, Please Stay - Nothing But Thieves)": '"My lover, please stay with me. Oh, my lover, please stay with me."',
      "(9 - Willow)": '"When I could just lay all day, with you. When I could just stay all day, with you."',
      "(All I Really Want Is You - The Marias)": '"All I really want is you. Laying in the rain with you."',
      "(All of Me - John Legend)": '"Love your curves and all your edges. All your perfect imperfections."',
      "(All of Me - John Legend)": '"Give your all to me, I will give my all to you. You are my end and my beginning."',
      "(All of Me - John Legend)": '"Cause I give you all of me. And you give me all of you."',
      "(All That Matters - dvsn)": '"You make me complete. You are all that matters to me."',
      "(All That Matters - dvsn)": '"What is a king bed without a queen?"',
      "(Alone With You - Alina Baraz)": '"When your days are long. I will be at the end of all of them."',
      "(Alone With You - Alina Baraz)": '"Alone with you. I am home with you. No matter the place."',
      "(Alone With You - Alina Baraz)": '"I have grown with you. Yet our love stays the same."',
      "(ARE YOU FEELING IT TOO? - syd B)": '"I can see it in your eyes, no, you are not alone, no."',
      "(Best Thing - Janine)": '"I want you in my life, that will not change if we are not together."',
      "(Best Thing - Janine)": '"You are the best thing, you are the best thing. That has happened to me in a while."',
      "(Best Thing - Janine)": '"Handed me the map to help me find myself. Made sure that I know I do not need no one else."',
      "(Best Thing - Janine)": '"There is not a title that can match our vibe. But whatever we call it just know you changed my life."',
      "(Best Thing - Janine)": '"You are still the best thing. My best friend, my everything."',
      "(Big Jet Plane - Angus & Julia Stone)": '"Gonna hold ya. Gonna kiss you in my arms. Gonna take ya. Away from harm."',
      "(Bouquets - Yumi Nu)": '"You know you are the best I have ever had. I know I am the best you have ever had."',
      "(call me when ur lonely - Alaina Castillo)": '"Call me when you need me that way. Call me when you want me. Anything to see your face."',
      "(Can I - Alina Baraz)": '"I bet you never even knew. I see the universe inside of you."',
      "(Can I - Alina Baraz)": '"Can I take your pain and make it go away? Would you let me be your getaway?"',
      "(Can I - Alina Baraz)": '"If I color you with all my thoughts. Would you lose your fears of being lost?"',
      "(Can't Stop - OneRepublic)": '"I said I can not stop. Thinking about, thinking about us. Anymore."',
      "(Can't Stop - OneRepublic)": '"I do not want to live without you. And put life off for another day."',
      "(Can't Take My Eyes off You - Craymer)": '"You are just too good to be true. Can not take my eyes off you."',
      "(Can't Take My Eyes off You - Craymer)": '"You would be like heaven to touch. I wanna hold you so much."',
      "(Can't Take My Eyes off You - Craymer)": '"At last long love has arrived. And I thank God, I am alive."',
      "(Can't Take My Eyes off You - Craymer)": '"Pardon the way that I stare. There is nothing else to compare."',
      "(Can't Take My Eyes off You - Craymer)": '"The sight of you leaves me weak. There are no words left to speak."',
      "(Can't Take My Eyes off You - Craymer)": '"I love you baby. And if it is quite all right. I need you baby. To warm the lonely nights."',
      "(Can't Take My Eyes off You - Craymer)": '"Oh, pretty baby. Now that I have found you stay. And let me love you, baby."',
      "(Come Here - Sabrina Claudio)": '"I want you to come here. I just need you near. No matter how, just make it here."',
      "(Come Here - Sabrina Claudio)": '"I am dying to see you. You know what I am fiending for. The only one to get to me."',
      "(Come Over - Jorja Smith)": '"I do not know what you have been through. But I worked too hard not to lose you, and you know that."',
      "(Deserve You - Justin Bieber)": '"I need you, do not let me go, need you, do not let me go."',
      "(Deserve You - Justin Bieber)": '"I need you more than I let you believe, I do. Cause you could think it might be too much."',
      "(Deserve You - Justin Bieber)": '"Oh, when we kiss I am alive, and I feel brand new. There is nothing that I want more than us."',
      "(Deserve You - Justin Bieber)": '"And now my eyes are locked on you. As you dance around the room. And finally, I am right where I belong."',
      "(Where Do Lovers Go? - Ghostly Kisses)": '"Will you hold on, my love, even in a time of trouble? I want to hold on, my love, even in times of trouble."',
      "(Desire - Years & Years)": '"I want you to want me again."',
      "(Don't Make Me Wait - Sabrina Claudio)": '"I have been feeling for your loving. Tired of waiting, give me something."',
      "(Don't Make Me Wait - Sabrina Claudio)": '"Would you hold me? Maybe kiss me? I have been wondering, did you miss me?"',
      "(Down For You - Alina Baraz)": '"Falling for you. I can not keep away. Are you listening? I want you to stay."',
      "(Down For You - Alina Baraz)": '"Before you go, I want you to know that. I am down, down, for you."',
      "(Dreams Tonite - Alvvays)": '"If I saw you on the street. Would I have you in my dreams tonite, tonite?"',
      "(Drive - Ray Silvers)": '"Maybe it is the way I feel when I am with you. Maybe it is the way you smile when you are asleep."',
      "(Drugs N Hella Melodies - Don Toliver)": '"I just wanna see you through the good and bad. Take you as you are and never give you back."',
      "(Electric - Alina Baraz)": '"Whisper in my ear, I am the only one you loving on. Take advantage of the moment, you are the only one that I want."',
      "(Electric - Alina Baraz)": '"Kiss me, we are on fire, babe. Love me, take me to outer space."',
      "(Endlessly - Alina Baraz)": '"Endlessly, you and me, all I need. Endlessly, you and me, all I need."',
      "(Every Pore - Tamino)": '"Darling, just calm me with your voice. Let your heart sing, how I always enjoy."',
      "(everything - Kehlani)": '"But your love is too original. You are anything, but conventional."',
      "(everything - Kehlani)": '"Love the way you teach me. Love the way you listen. You know all my details. You so damn attentive."',
      "(everything - Kehlani)": '"I match your energy, match your fly perfectly. Lips lock intensively, want you extensively."',
      "(Feels Right - Alina Baraz)": '"You feel like heaven to me. And everything in between."',
      "(Floating - Alina Baraz)": '"You know that I will not let go. You have got me on repeat. You have got me in a dream."',
      "(Floating - Alina Baraz)": '"Everything you do. I wanna do it with you. Do not ever wanna miss you."',
      "(Frank - Alina Baraz)": '"Take me to the place. Where we will never fade. Underneath the stars. Love me in the dark."',
      "(Frank - Alina Baraz)": '"I look at you and I see. All the parts of me. Swaying to the beat. Lost in your melody. I swear."',
      "(Frozen - Sabrina Claudio)": '"If we could live in this moment. And just hold it. Keep my head on your chest. I will never leave this bed."',
      "(Global Warming - Sasha Alex Sloan)": '"When you hold me just like this. When you lean in for a kiss. Your love makes me forget, Bad things exist."',
      "(Heaven - FINNEAS)": '"Heaven is not as wonderful. Heaven, is not as beautiful as you."',
      "(I Know How To Speak - Manchester Orchestra)": '"I, I am really gonna try this time. Gonna give you my heart in spite of my soul."',
      "(I Know How To Speak - Manchester Orchestra)": '"I want your name. Burnt in my ceiling. Floats like a flame. An unpredictable wonder."',
      "(i wanna be your girlfriend - gglum)": '"Oh, Hannah, I want to feel you close, come lay with my bones, do not look away, just look at me the same."',
      "(i wanna be your girlfriend - gglum)": '"I do not want to be your friend, I want to kiss your lips. I wanna kiss you until I lose my breath."',
      "(I Want You - Dasilva)": '"I want you. Can you hear me baby? Can you hear my voice? I need you. Can you hear me baby? Can you hear my cry?"',
      "(Love song - Lana Del Rey)": '"The taste, the touch, the way we love. It all comes down to make the sound of our love song."',
      "(Love song - Lana Del Rey)": '"Would like to think that you would stick around. You know that I would just die to make you proud."',
      "(Love song - Lana Del Rey)": '"Oh, be my once in a lifetime."',
      "(Love Song - Madisenxoxo)": '"I wanna love you until the day that I die."',
      "(Love Song - Madisenxoxo)": '"Lets get a dog. Move somewhere boring. Make it better. Two cats in the yard."',
      "(Love Song - Madisenxoxo)": '"I do not need money. Do not need alcohol. I just want you. Covered in me. Under the covers. You and me forever."',
      "(Lucid - QUIN)": '"You can just hang on, I will be the cure. You will not have to worry anymore. Hold on to me, it will not be long with me."',
      "(Lucky Ones - Lana Del Rey)": '"Everybody told me love was blind. Then I saw your face and you blew my mind."',
      "(Meaningless - Charlotte Cardin)": '"I do not wanna live, a meaningless. I do not wanna live, a meaningless life without you."',
      "(Meet Me in Amsterdam - RINI)": '"I found the love the warmth in your arms. I do not need anything, I just want you."',
      "(Morning After - dvsn)": '"You are the one I want, one I want to stay the morning."',
      "(My Love - maye)": '"You say you will stay with me forever. But I think forever does not seem like it is enough."',
      "(Naked - Sabrina Claudio)": '"All of me is all for you. Uncover all of my truths. Undress my fears, leave me nude."',
      "(Never Enough - Black Atlass)": '"I wanna feel you next to me. Baby I need your energy. Nothing else can break me. Like your touch."',
      "(Never Enough - Black Atlass)": '"All I need is your touch. Somehow it is never enough. All I need is your touch. I will give you all that I have got."',
      "(Path - LUAMEL)": '"You were my path. What was I to you? Forever I wished to stay by, your side."',
      "(Bending Light - Beacon)": '"And I feel you with me, so I hold on tight."',
      "(Northern Lights - Kennie)": '"Wonder if you see me. In another lifetime, I kissed your cheek and said that, I would rather stay here by your side."',
      "(Northern Lights - Kennie)": '"You are totally astronomical, brighter than the Northern Lights. You are in every color, in this star-speckled sky. And I just want you here with me."',
      "(Only in My Dreams - The Marias)": '"You are everything I need to bare this fear. The demons in my bed, they are always here. It is only just a dream."',
      "(Cornflower Blue - Flower Face)": '"I love you until I wear you out, then I love you more."',
      "(Cornflower Blue - Flower Face)": '"I will not let you out of my sight, even when you are sleeping. So baby, take your medicine, and promise me you are eating."',
      "(Love Me Wrong - Isak Danielson)": '"So love me wrong, if you can not love me right. All I want is to be in your vice."',
      "(Love Me Wrong - Isak Danielson)": '"You are the one who builds my paradise. Love me, love me wrong, if you can not love me right."',
      "(PPP - Beach House)": '"Someone once told me. In love, that you must, place all you are given, in infinite trust."',
      "(Problem With You - Sabrina Claudio)": '"The problem with you is, that I can not get you off my mind. And I think about you all the time."',
      "(Problem With You - Sabrina Claudio)": '"The problem with you is, that you are all that I dream about. And you are not right here right now."',
      "(Right There - Alina Baraz)": '"I am gonna need you right there. I am gonna need you right there, right there with me. Right there with me, right there."',
      "(Run Away With Me - Carly Rae Jepsen)": '"You are stuck in my head, stuck on my heart, stuck on my body, body. I would run away, I would run away with you."',
      "(Save Room for Us - Tinashe)": '"You know it is not the end. We will fall in love again. Cause we were built in dreams of gold."',
      "(Save Room for Us - Tinashe)": '"And it may not be today. True love will find a way. Just save a space for me."',
      "(She's So Lovely - Beach House)": '"She is so lovely, everything about her. She is so lovely, everything about her."',
      "(Sleep On The Floor - The Lumineers)": '"Leave a note on your bed. Let your mother know you are safe. And by the time she wakes, We will have driven through the night."',
      "(Stars And Moons - Dizzy)": '"Baby, it is a dog day, do not you let it rule, Cause I could hold your whole weight if you asked me to."',
      "(Stay - GITAA)": '"Ohhh, I want you to stay, I want you to stay, I want you to stay. I want you to stay with me."',
      "(Story Of Us - Tinashe)": '"Yeah, you are the prince of my heart. And now there is no way they gonna keep us apart, keep us apart."',
      "(Story Of Us - Tinashe)": '"Yeah, we built a castle of trust. And I am your queen to be, now the story of us about to start."',
      "(Story Of Us - Tinashe)": '"Once upon a time you are mine. Once upon a time we start to fall...in love."',
      "(Subside - Summer Heart)": '"Do not tell me it is over. I will wait for you, I will wait for you. Put it on a plate for you, I will wait for you."',
      "(Sway - Majid Jordan)": '"I want you to sway, I want you to sway. I want you to let the record play. Let the record state, I love you. I need you. I want you."',
      "(Sweet - Majid Jordan)": '"You are my winter, you are my spring. In the morning you are all I am seeing. Pull me closer and let me in."',
      "(Sweet - Majid Jordan)": '"Sing a song from your heart, and I will love you. Leave a space in your heart for me."',
      "(Take It Home - Alina Baraz)": '"You say that you want someone to hold. I just wanna get you all alone."',
      "(Tell Me - Sabrina Claudio)": '"Help me understand you love. Help me go the way you want me to go, cause I can not guess the things you are thinking so."',
      "(Tell Me - Sabrina Claudio)": '"Help me understand you love. Tell me everything you want me to know, cause I can not fix it until I know that it is broke."',
      "(Therapy - noelle)": '"When you smile, your eyes light up like a fire."',
      "(Therapy - noelle)": '"Lately it is been hard, and we got nothing to talk about. But I will not give up, let us work it out."',
      "(Therapy - noelle)": '"I am on your side, through the dark nights, and the hard times. If you cry, I will dry your eyes."',
      "(Therapy - noelle)": '"I want you to talk about, the way you feel inside . You will always be safe with me."',
      "(Therapy - noelle)": '"Just put your hand in mine. Just let me be your therapy tonight. So let me be your therapy tonight."',
      "(Therapy - noelle)": '"Lately you have been distant, gonna try my best to fix it. I will not give up, until we work it out."',
      "(There You Are - ZAYN)": '"Only you know me the way you know me. Only you forgive me when I am sorry."',
      "(There You Are - ZAYN)": '"Need you when I am broken, when I am fixed. Need you when I am well, when I am sick."',
      "(There You Are - ZAYN)": '"Need you when I am hot, when I am cold. Need you when I am young, when I am old."',
      "(Thinking About You - HANDS)": '"I can not stop thinking about you. You are on my mind, all the time. You are everywhere, in everything."',
      "(This Love - Taylor Swift)": '"This love left a permanent mark. This love is glowing in the dark."',
      "(Trust - Alina Baraz)": '"Look all around you. Damn, I am so lucky I found you."',
      "(Trust - Alina Baraz)": '"We good for each other. I will not put no one above ya, I will not put no one in front of ya."',
      "(Untouchable - Taylor Swift)": '"It is like a million little stars spelling out your name. You gotta come on, say that we will be together, little taste of heaven."',
      "(Ways Of Love - Bahari)": '"I am in your hands. Show me the ways of love, and I will follow. I love you!"',
      "(Ways Of Love - Bahari)": '"I might give in. The sound of your ocean. The smell of your skin."',
      "(When I'm Loving You - Yianna)": '"Ever since I saw your face. My whole world has been changing. I have been rearranging the songs I sing."',
      "(When I'm Loving You - Yianna)": '"When I am loving you, I feel like I am alive. For the very first time, I am seeing blue, feeling red."',
      "(When I'm Loving You - Yianna)": '"When I am loving you, I find it hard to breathe, can not find the words to speak."',
      "(When I'm Loving You - Yianna)": '"When I am loving you, I used to see in shades of grey, but then color came through the second I saw you."',
      "(Wildest Dreams - Majid Jordan)": '"It is a dream come true. I find it hard to believe. It is a miracle God gave me you. I find it hard to believe."',
      "(Wildest Dreams - Majid Jordan)": '"All my wildest dreams. Got nothing on you, nothing on you."',
      "(You Never Loved - Daniele Luppi)": '"I am falling. I am dreaming of you again, but I can not sleep, until I hear your voice."',
      "(You Never Loved - Daniele Luppi)": '"You are smiling. And I remember every word, that you said, when you held my hand."',
      "(Yours - maye)": '"Let us go, to another coast. Take me somewhere we can be alone. Baby, that way we will get comfortable."',
      "(Yours - maye)": '"I really wanna let you know, that I can never let you go, cause I just wanna be only yours."',
      "(Yours - maye)": '"And maybe I will surrender, cause loving you is better. It is not worth it to fight it, I am giving up."',
      "(Desert Rose - Lolo Zouai)": '"Love me like a desert rose. Hold me like you can not let go. Keep me safe when I come home."',
      "(Lost - Sarah Proctor)": '"I do not wanna be somewhere you are not, cause baby, I just wanna get lost with you."',
      "(Lost - Sarah Proctor)": '"It is just you and me tonight. We put the seats back, then we just talk, about the future and all of our thoughts."',
      "(Oh Caroline - The 1975)": '"Baby, I will do anything that you wanna. I will try anything that you wanna, I will try, cause you are on my mind."',
      "(Oh Caroline - The 1975)": '"I wanna get it right this time, cause you are always on my mind."',
      "(Oh Caroline - The 1975)": '"Just give me one more chance tonight, cause I do not want to waste my life without you, baby."',
      "(More - The Greeting Committee)": '"Do not need much, but I need your loving. Oh, I have been so down without you around."',
      "(More - The Greeting Committee)": '"You are making me love you more, than all of the days before. Know I love you more. Know I love you more."',
      "(More - The Greeting Committee)": '"You are making me better than, who I ever could have been on my own. Swear that I love you more. Just Know that I love you more."',
      "(I Think About You - BLU J)": '"In my subconscious mind, I think about you all of the time. Every dream you occupy, I think about you."',
      "(I Think About You - BLU J)": '"You are beautiful and disastrous. It is unusual but I can not resist you. No I can not resist you."',
      "(Love You Like That - Arctic Lake)": '"I need you right back here. Come let me adore you. Baby, let me explore you. Let me drive you mad. I can love you like that."',
      "(Love You Like That - Arctic Lake)": '"Do not say we are over again. Just say you love me instead."',
      "(my time - Zubi)": '"Babe hold me tight. Do not think twice. Do not deny. This feels right. I know you are shy. Hold me close. Do not let go."',
      "(my time - Zubi)": '"You keep me float. you are my soul. You make me grow, that is why you see this glow."',
      "(my time - Zubi)": '"Kiss me please. Let them see. Let me feel. This love is real. This love is chill. I was made for this."',
      "(Intoxicated - Black Atlass)": '"When I feel your heartbeat I follow the sound. Your love could lift any man off the ground."',
      "(Intoxicated - Black Atlass)": '"As long as we are together I am found. And I am just lucky you are around. I was focused on the wrong things till I saw you."',
      "(Intoxicated - Black Atlass)": '"Oh baby, your love is so gorgeous. And I hope I can afford you. Do not leave me in the morning."',
      "(Intoxicated - Black Atlass)": '"I can not go all night long without you, cause a broken heart is all I have ever known."',
      "(Touch - Ghostly Kisses)": '"Every day, I keep thinking, about you and I, how good we are together, when we are alone together."',
      "(Touch - Ghostly Kisses)": '"I wanna feel your touch. I wanna feel you. I wanna feel your touch. I wanna feel you. Will you ever Let me in?"',
      "(You & I - MIRA)": '"I hurt you, I know I did, I never meant to. Just hold me, I know that we are both broken inside, but in the end, it is you and I, you and I."',
      "(Pointless - Lewis Capaldi)": '"From all my airs and graces. To the little things I do. Everything is pointless without you."',
      "(Pointless - Lewis Capaldi)": '"Of all the dreams I am chasing. There is only one I choose. Everything is pointless without you."',
      "(Pointless - Lewis Capaldi)": '"I bring her coffee in the morning. She brings me inner peace."',
      "(Pointless - Lewis Capaldi)": '"I light the fire when it is cold out. And she lights up the room."',
      "(Pointless - Lewis Capaldi)": '"I hope that she will love me forever. She hopes I will be back soon."',
      "(Pointless - Lewis Capaldi)": '"I take her out to the movies. She takes away my pain."',
      "(Pointless - Lewis Capaldi)": '"She is the start of everything. And I will be there til the end."',
      "(Pointless - Lewis Capaldi)": '"I love when she laughs for no reason. And her love is the reason I am here."',
      "(Pointless - Lewis Capaldi)": '"I will wait for you. I will wait for you. You will wait for me too."',
      "(Particles - Nothing But Thieves)": '"Baby, tell me if I am being strange. And if I need to rearrange my particles, I will for you. My particles, I will for you."',
      "(Piece of Your Heart - Melis)": '"My love is waiting on you still. So will you let me in?"',
      "(Piece of Your Heart - Melis)": '"Do not need a peace of mind if I got a piece of your heart."',
      "(Piece of Your Heart - Melis)": '"Do not leave me in the dark, I would tear myself apart. Just to have a piece of your heart."',
      "(Stars Were Made For Us - Bella Goldwin)": '"Do you believe that I am the one? Or the stars were made for us?"',
      "(Stars Were Made For Us - Bella Goldwin)": '"Come into me before it is gone. Our lives will not last for long."',
      "(Stars Were Made For Us - Bella Goldwin)": '"There is a world beyond here I know we will find. Only love can make us fly."',
      "(Stars Were Made For Us - Bella Goldwin)": '"Let us get out of here no more wasting time. We were born to live our lives. Take a leap of faith with me."',
      "(Stars Were Made For Us - Bella Goldwin)": '"Do not you think we can reach the stars? Never let my hand go. I will take you far beyond where we are. Take a leap of faith with me."',
    };
  
    // grab all the keys in the dictionary (authors) and store in an array
    var authors = Object.keys(quotes);
    // grab a random key (author) and store it in author
    var author = authors[Math.floor(Math.random() * authors.length)];
    // grab the value(quote) that belongs to that key
    var quote = quotes[author]
  
    document.querySelector("#quote").textContent = quote;
    document.querySelector("#author").textContent = author;
  
  }